/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Multisig } from "./Multisig";

export { Multisig__factory } from "./factories/Multisig__factory";
